/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthAdminRouteImport } from './routes/_auth/admin'
import { Route as AuthBrowseRouteImport } from './routes/_auth/browse'
import { Route as AuthLibraryRouteImport } from './routes/_auth/library'
import { Route as AuthSearchRouteImport } from './routes/_auth/search'
import { Route as AuthTitleIdRouteImport } from './routes/_auth/title.$id'
import { Route as AuthWatchIdRouteImport } from './routes/_auth/watch.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBrowseRoute = AuthBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLibraryRoute = AuthLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSearchRoute = AuthSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTitleIdRoute = AuthTitleIdRouteImport.update({
  id: '/title/$id',
  path: '/title/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWatchIdRoute = AuthWatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthAdminRoute
  '/browse': typeof AuthBrowseRoute
  '/library': typeof AuthLibraryRoute
  '/search': typeof AuthSearchRoute
  '/title/$id': typeof AuthTitleIdRoute
  '/watch/$id': typeof AuthWatchIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin': typeof AuthAdminRoute
  '/browse': typeof AuthBrowseRoute
  '/library': typeof AuthLibraryRoute
  '/search': typeof AuthSearchRoute
  '/': typeof AuthIndexRoute
  '/title/$id': typeof AuthTitleIdRoute
  '/watch/$id': typeof AuthWatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/admin': typeof AuthAdminRoute
  '/_auth/browse': typeof AuthBrowseRoute
  '/_auth/library': typeof AuthLibraryRoute
  '/_auth/search': typeof AuthSearchRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/title/$id': typeof AuthTitleIdRoute
  '/_auth/watch/$id': typeof AuthWatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/browse'
    | '/library'
    | '/search'
    | '/title/$id'
    | '/watch/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin'
    | '/browse'
    | '/library'
    | '/search'
    | '/'
    | '/title/$id'
    | '/watch/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/admin'
    | '/_auth/browse'
    | '/_auth/library'
    | '/_auth/search'
    | '/_auth/'
    | '/_auth/title/$id'
    | '/_auth/watch/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/browse': {
      id: '/_auth/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AuthBrowseRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/library': {
      id: '/_auth/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthLibraryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/search': {
      id: '/_auth/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthSearchRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/title/$id': {
      id: '/_auth/title/$id'
      path: '/title/$id'
      fullPath: '/title/$id'
      preLoaderRoute: typeof AuthTitleIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/watch/$id': {
      id: '/_auth/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof AuthWatchIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRoute
  AuthBrowseRoute: typeof AuthBrowseRoute
  AuthLibraryRoute: typeof AuthLibraryRoute
  AuthSearchRoute: typeof AuthSearchRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthTitleIdRoute: typeof AuthTitleIdRoute
  AuthWatchIdRoute: typeof AuthWatchIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRoute,
  AuthBrowseRoute: AuthBrowseRoute,
  AuthLibraryRoute: AuthLibraryRoute,
  AuthSearchRoute: AuthSearchRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthTitleIdRoute: AuthTitleIdRoute,
  AuthWatchIdRoute: AuthWatchIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
